- name: copy rpm to nodes
  copy: src={{ item }} dest=/usr/local/src/
  with_fileglob:
    - /root/rpmbuild/RPMS/x86_64/torque*.rpm

- lineinfile: dest=/etc/hosts line="{{ server_IP }} {{ server_hostname }}"

- file: src=nodes dest=/var/spool/torque/server_priv/nodes
  when: inventory_hostname == "{{ server_hostname }}"
  
- template: src=server_name.j2 dest=/var/spool/torque/server_name

- template: src=config.j2 dest=/var/spool/torque/mom_priv/config

- name: install torque rpm
  yum: name={{ item }}
  with_fileglob:
    - /usr/local/src/torque*.rpm
  when: inventory_hostname == "{{ server_hostname }}"

- name: install torque rpm
  yum: name={{ item }}
  with_fileglob:
    - /usr/local/src/torque-6.0.1-1.adaptive.el7.centos.x86_64.rpm
    - /usr/local/src/torque-client-6.0.1-1.adaptive.el7.centos.x86_64.rpm
    - /usr/local/src/torque-debuginfo-6.0.1-1.adaptive.el7.centos.x86_64.rpm
  when: inventory_hostname != "{{ server_hostname }}"

- service: name=trqauthd state=started enabled=yes

- service: name={{ item }} state=started enabled=yes
  with_items:
    - pbs_server
    - pbs_sched
  when: inventory_hostname == "{{ server_hostname }}"

- service: name=pbs_mom state=started enabled=yes
  when: inventory_hostname != "{{ server_hostname }}"
  

  
  