#!/bin/bash
user=$1
userid=$2
groupid=$3

enpass=$(/usr/local/bin/retrieve_pass $user)
# /data dir docker run -d -v /proj_dir:/mnt/encry1
mkdir -p /data
chown -R $userid:$groupid /data
chmod 0700 /data

echo $enpass | encfs /mnt/encry1 /data -o uid=$userid -o gid=$groupid

# /scratch dir docker run -d -v $scratch:/mnt/encry2
#mkdir -p /scratch
#chown -R $userid:$groupid /scratch
#chmod 0700 /scratch

#echo $enpass | encfs /mnt/encry2 /scratch -S -o uid=$userid -o gid=$groupid
