#!/bin/bash

user=$1
userid=$2
groupid=$3

cat /etc/upasswd >> /etc/passwd
cat /etc/ugroup >> /etc/group

enpass=$(/usr/local/bin/retrieve_pass $user)
# /data dir docker run -d -v /proj_dir:/mnt/encry1
mkdir -p /data
chown $userid:$groupid /data
usermod -d /data $user

#runuser -l $user -c "echo $enpass | encfs /mnt/encry1 /data -S -o uid=$userid -o gid=$groupid"
echo $enpass | encfs /mnt/encry1 /data -S --public
chmod 0700 /data

# /scratch dir docker run -d -v $scratch:/mnt/encry2
#mkdir -p /scratch
#chown -R $userid:$groupid /scratch
#chmod 0700 /scratch

#echo $enpass | encfs /mnt/encry2 /scratch -S -o uid=$userid -o gid=$groupid
