- name: copy slurm rpm to nodes
  copy: src={{ item }} dest=/usr/local/src/
  with_fileglob:
    - /root/rpmbuild/RPMS/x86_64/slurm*.rpm
        
- lineinfile: dest=/etc/hosts line="{{ slurmctld_IP }} {{ slurmctld_hostname }}"

- name: install munge
  yum: name=munge
  
- name: copy munge key to host
  copy: src=/etc/munge/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=0600 force=yes

- name: start munge service
  service: name=munge state=started enabled=yes
  
- name: install slurm rpm
  yum: name={{ item }}
  with_fileglob:
    - /usr/local/src/slurm*.rpm

- name: create slurm system user
  user: name=slurm shell=/bin/false system=yes

- name: create state save location
  file: path={{ state_save_location }} state=directory owner=slurm group=slurm mode=0755
  
- name: copy slurm conf file
  template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf mode=0644
  notify: restart_slurm

- name: start slurm service
  service: name=slurm state=started enabled=yes


    

