#!/bin/bash

user=$LOGNAME

# create private overlay network for each user for running jobs
if ! docker network inspect net-$user &> /dev/null ; then
    docker network create -d overlay net-$user &> /dev/null
fi

check_container(){
    docker inspect --format="{{ .State.Running }}" login-$user &> /dev/null
}

if ! check_container ; then
    docker pull 10.0.15.16:5000/login &> /dev/null
    docker run -i --rm --hostname $HOSTNAME -P \
	   --add-host=test3:10.0.15.13 \
	   -v /home/$user/encrypted:/mnt/do_not_use \
           -v /opt:/opt:ro \
	   -v /etc/passwd:/etc/passwd:ro \
	   -v /etc/group:/etc/group:ro \
	   -v /home/$user \
           -v /opt:/opt:ro \
	   --net net-$user \
	   --cap-drop FOWNER --cap-drop SETPCAP --cap-drop SETFCAP --cap-drop MKNOD \
	   --cap-add SYS_ADMIN --device /dev/fuse \
	   --name login-$user 10.0.15.16:5000/login \
	   $user &> /dev/null &
fi

while :; do
    if check_container ; then
	break
    fi
    sleep 0.5
done

docker port login-$user 22 | awk -F: '{print $2}'



