#!/bin/bash

user=$1

check_compute(){
    docker inspect --format="{{ .State.Running }}" compute-$user &> /dev/null
}

if ! check_compute ; then
  docker run -i --rm --hostname $HOSTNAME -P \
       -v /home/$user:/mnt/do_not_use \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -v /home/$user \
       --cap-drop FOWNER --cap-drop SETPCAP --cap-drop SETFCAP --cap-drop MKNOD \
       --cap-add SYS_ADMIN --device /dev/fuse \
       --name compute-$user compute \
       $user &> /dev/null &
fi

while :; do
    if check_compute ; then
	break
    fi
    sleep 0.5
done

docker port compute-$user 22 | awk -F: '{print $2}'



