#!/bin/bash

sctld_host=`scontrol show hostnames $SLURM_JOB_NODELIST | head -n1`
nfsd_host=`scontrol show hostnames $SLURM_JOB_NODELIST | tail -n1`

ssh $sctld_host "docker network create -d overlay stack$SLURM_JOB_ID"
ssh $sctld_host "docker run -d --name slurmctld-$SLURM_JOB_ID --net stack$SLURM_JOB_ID slurmctld_image"
ssh $nfsd_host "docker run -d --name shadow --net stack$SLURM_JOB_ID nfsd_image"

nfsd_ip=`docker inspect -f "{{ .NetworkSettings.Networks.stack$SLURM_JOB_ID.IPAddress }}" shadow`

for i in `scontrol show hostnames $SLURM_JOB_NODELIST`; do
    ssh  $i "docker run -d --name slurmd-$SLURM_JOB_ID-$SLURMD_NODENAME --net stack$SLURM_JOB_ID slurmd_image "
done






