#!/bin/bash

user=$1

cat /etc/upasswd >> /etc/passwd
cat /etc/ugroup >> /etc/group

sed -i "/SlurmUser=/c\SlurmUser=$user" /etc/slurm/slurm.conf
sed -i "/SlurmdUser=/c\SlurmdUser=$user" /etc/slurm/slurm.conf

runuser -l $user -c '/usr/sbin/slurmctld -D -v -c &> /var/log/slurmctld.log &'

