#!/bin/bash

function sub_job(){
qsub << 'EOF'
#PBS -l walltime=00:20:00
sleep 1200
EOF
}

jobid=$(sub_job)

sleep 5
mhost=`qstat -f $jobid | grep exec_host | awk -F= '{print $2}' | awk -F/ '{print $1}'`

echo granted $mhost for job $jobid
echo ssh-ing to $mhost

while :; do
    if ssh -q $mhost date &> /dev/null ; then
	break
    fi
    sleep 1
done

ssh $mhost
