#!/bin/bash

user=$LOGNAME
cname=login-$user

# create private overlay network for each user for running jobs
if ! docker network inspect net-$user &> /dev/null ; then
    docker network create -d overlay net-$user &> /dev/null
    logger $0: User $user created docker overlay network net-$user
fi

check_container(){
    docker inspect --format="{{ .State.Running }}" $cname &> /dev/null
}

check_mount(){
    docker exec -i $cname grep "encfs /home/$user" /proc/mounts &> /dev/null
}

if ! check_container ; then
    docker pull 10.0.15.16:5000/login &> /dev/null
    docker run -i --rm --hostname $HOSTNAME -P \
	   --add-host=test3:10.0.15.13 \
	   -v /home/$user/encrypted:/mnt/do_not_use \
           -v /opt:/opt:ro \
	   -v /etc/passwd:/etc/passwd:ro \
	   -v /etc/group:/etc/group:ro \
	   -v /home/$user \
           -v /opt:/opt:ro \
	   --net net-$user \
	   --cap-drop FOWNER --cap-drop SETPCAP --cap-drop SETFCAP --cap-drop MKNOD \
	   --cap-add SYS_ADMIN --device /dev/fuse \
	   --name $cname 10.0.15.16:5000/login \
	   $user &> /dev/null &
    logger $0: User $user started a docker container $cname
fi

while :; do
    if check_mount ; then
	break
    fi
    sleep 1
done

docker port $cname 22 | awk -F: '{print $2}'



